---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: globy-frontend-deploy
  namespace: ${K8S_NAMESPACE}
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ${IMAGE_NAME}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: recred
---
apiVersion: v1
kind: Service
metadata:
  namespace: ${K8S_NAMESPACE}
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: globy-frontend-ingress
  namespace: ${K8S_NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  rules:
  - host: ${K8S_INGRESS_HOST}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-service
            port:
              number: 8080
