name: Deploy to K8s

on:
  push:
    branches: [ prod, dev ]

env:
  IMAGE_NAME: ghcr.io/therzarzayev/globy/globy-frontend:${{ github.ref_name }}-${{ github.run_number }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Set K8s Env Vars
      run: |
        echo "K8S_NAMESPACE=$( [[ '${{ github.ref_name }}' == 'main' ]] && echo 'globy-prod' || echo 'globy-dev' )" >> $GITHUB_ENV
        echo "FRONTEND_IMAGE=$IMAGE_NAME:${{ github.ref_name }}" >> $GITHUB_ENV
        echo "K8S_INGRESS_HOST=$( [[ '${{ github.ref_name }}' == 'main' ]] && echo 'globy.space' || echo 'dev.globy.space' )" >> $GITHUB_ENV

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure Kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        envsubst < deploy/k8s.template.yaml > deploy/k8s.yaml
        kubectl apply -f deploy/k8s.yaml
